apiVersion: batch/v1
kind: Job
metadata:
  name: yes-mlflow
spec:
  template:
    spec:
      containers:
        - name: training
          image: mlflow-training:latest
          imagePullPolicy: Never
          command: ["python", "train.py"]
          env:
            - name: HOST_IP
              value: "mlflow"
            - name: MLFLOW_PORT
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: port
            - name: MLFLOW_EXPERIMENT_NAME
              value: "Simple Logistic Regression"
      restartPolicy: Never
