apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-config
data:
  port: "5000"  # Single source of truth for the port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.11.0
        ports:
        - containerPort: 5000
        command:
        - mlflow
        - server
        - --host=0.0.0.0
        - --port=$(MLFLOW_PORT)  # Use environment variable
        - --backend-store-uri=sqlite:///mlflow.db
        - --default-artifact-root=/mlruns
        - --serve-artifacts
        env:
        - name: MLFLOW_PORT
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              key: port
        - name: MLFLOW_TRACKING_USERNAME
          value: ""
        - name: MLFLOW_TRACKING_PASSWORD
          value: ""
        - name: MLFLOW_TRACKING_TOKEN
          value: ""
        volumeMounts:
        - name: mlflow-data
          mountPath: /mlruns
      volumes:
      - name: mlflow-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
  - port: 5000
    targetPort: 5000  # This matches the containerPort
    nodePort: 30505